# Generated by Django 3.2.3 on 2021-06-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_cracao',
            new_name='data_criacao',
        ),
    ]
